CREATE TABLE IF NOT EXISTS Genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS MpaRating(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(200)
);
CREATE TABLE IF NOT EXISTS "User"(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(200),
    user_login VARCHAR(100),
    user_name VARCHAR(100),
    user_birthday DATE,
    CONSTRAINT login_without_space CHECK (user_login NOT LIKE '% %'),
    CONSTRAINT not_future_born_man CHECK (user_birthday <= CURRENT_DATE)
);
CREATE TABLE IF NOT EXISTS Film(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(200),
    film_description VARCHAR(200),
    film_release_date DATE,
    film_duration SMALLINT,
    mpa_rating_id SMALLINT,
    FOREIGN KEY (mpa_rating_id) REFERENCES MpaRating(rating_id),
    CONSTRAINT film_min_date CHECK (film_release_date >= '1895-12-28'),
    CONSTRAINT film_duration_positive CHECK (film_duration > 0)
);

CREATE TABLE IF NOT EXISTS FilmGenres(
    film_id INTEGER,
    genre_id SMALLINT,
    FOREIGN KEY (genre_id) REFERENCES Genre(genre_id),
    CONSTRAINT unique_film_genre UNIQUE (film_id,genre_id)
);

CREATE TABLE IF NOT EXISTS UserFriends(
    user_id INTEGER,
    friend_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES "User"(user_id),
    FOREIGN KEY (friend_id) REFERENCES "User"(user_id),
    CONSTRAINT unique_friends UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS Likes(
    user_id INTEGER,
    film_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES "User"(user_id),
    FOREIGN KEY (film_id) REFERENCES Film(film_id),
    CONSTRAINT unique_likes UNIQUE (user_id, film_id)
);

