CREATE TABLE IF NOT EXISTS Genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS MpaRating(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(200)
);
CREATE TABLE IF NOT EXISTS "User"(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(200),
    user_login VARCHAR(100),
    user_name VARCHAR(100),
    user_birthday DATE
);
CREATE TABLE IF NOT EXISTS Film(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(200),
    film_description VARCHAR(200),
    film_release_date DATE,
    film_duration SMALLINT,
    genre_id SMALLINT,
    mpa_rating_id SMALLINT,
    FOREIGN KEY (genre_id) REFERENCES Genre(genre_id),
    FOREIGN KEY (mpa_rating_id) REFERENCES MpaRating(rating_id)
);

CREATE TABLE IF NOT EXISTS UserFriends(
    user_id INTEGER,
    friend_id INTEGER,
    accepted_request BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES "User"(user_id),
    FOREIGN KEY (friend_id) REFERENCES "User"(user_id),
    CONSTRAINT unique_friends UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS Likes(
    user_id INTEGER,
    film_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES "User"(user_id),
    FOREIGN KEY (film_id) REFERENCES Film(film_id),
    CONSTRAINT unique_likes UNIQUE (user_id, film_id)
);

